#! /bin/bash
echo typedef expr_reader = void *\;
echo typedef expr_writer = void *\;
echo typedef expr_argffetch = void *\;
echo typedef expr_allocator_type = void *\;
echo typedef expr_reallocator_type = void *\;
echo typedef expr_deallocator_type = void *\;
echo typedef expr_symbol_type = 'enum(EXPR_CONSTANT=0,EXPR_VARIABLE=1,EXPR_FUMCTION=2,EXPR_MDFUNCTION=3,EXPR_MDEPFUNCTION=4,EXPR_ZAFUNCTION=5,EXPR_HOTFUNCTION=6,EXPR_ALIAS=7)'\;
echo typedef expr_symbol_type_short = 'enum[short](EXPR_CONSTANT=0,EXPR_VARIABLE=1,EXPR_FUMCTION=2,EXPR_MDFUNCTION=3,EXPR_MDEPFUNCTION=4,EXPR_ZAFUNCTION=5,EXPR_HOTFUNCTION=6,EXPR_ALIAS=7)'\;
echo typedef struct_expr_builtin_symbol = 'struct(void *,string,ushort,expr_symbol_type_short,short,short)'\;
sed 's/__attribute__((.*)) //g' |
	sed 's/expr_static_assert/_/g' |
	grep '^[a-z].* [^(]*(.*);' |
	grep '^extern ' -v |
	grep '^typedef ' -v |
	sed 's/restrict //g' |
	sed 's/const //g' |
	sed 's/intptr_t/long/g' |
	sed 's/int64_t/long/g' |
	sed 's/int32_t/int/g' |
	sed 's/int16_t/short/g' |
	sed 's/uint8_t/char/g' |
	sed 's/int8_t/char/g' |
	sed 's/ssize_t/long/g' |
	sed 's/size_t/ulong/g' |
	sed 's/ptrdiff_t/long/g' |
	sed 's/char errinfo\[.*\]/string/g' |
	sed 's/struct expr_builtin_symbol/struct_expr_builtin_symbol/g' |
	sed 's/int type,int flag/expr_symbol_type,int/g' |
	sed 's/struct [^,(]*\*/void \*/g' |
	sed 's/union [^,(]*\*/void \*/g' |
	sed 's/va_list ap/void \*/g' |
	sed 's/,\.\.\.//g' |
	sed 's/ \*[^(,]*,/ \*,/g' |
	sed 's/ \*[^(,]*)/ \*)/g' |
	sed 's/ [^(,\*]*,/,/g' |
	sed 's/ [^(,\*]*)/)/g' |
	sed 's/char \*/string/g'
